# Default application configuration that all configurations inherit from.
linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DeclaredName:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyRule:
    enabled: true

  HexFormat:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 1

  LeadingZero:
    enabled: false

  PlaceholderInExtend:
    enabled: true

  PropertySpelling:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 3

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SortedProperties:
    enabled: false

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UsageName:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
